version: "3.8"
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: botronic
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    environment:
      VIRTUAL_HOST: testing.local
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public
      - ./storage/app/public:/app/public/storage

  php:
    build:
      target: dev
    depends_on:
      - composer
      - mysql
    volumes:
      - ./:/app
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./storage/app/public:/app/public/storage

  node:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"

  composer:
    image: composer:2.4
    working_dir: /app
    volumes:
      - ./:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts

volumes:
  db-data:
